# Use postgres/example user/password credentials 
version: '3.1' 
services: 
  db: 
    image: postgres:12 
    restart: always 
    environment: 
      POSTGRES_PASSWORD: example 
    ports: 
    - 5432:5432 
    networks: 
    - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  centos:
    image: centosxd
    ports:
    - 80:80
    networks: 
    - postgres
    depends_on:
      db:
        condition: service_healthy
networks: 
  postgres: 
    driver: bridge
